# --------------------------------------------------------------------------------------------------
# This GitHub Actions workflow file defines a reusable workflow that can be shared across jobs.
# It prepares the necessary configuration for the Firebase App Distribution service and places it
# into the proper location on the file system.
# --------------------------------------------------------------------------------------------------

name: Firebase App Distribution Configuration
description: Prepares Firebase App Distribution configuration

inputs:
    credentials_file:
        description: The path to the service account private key JSON file
        required: true
    groups:
        description: The tester groups you want to distribute builds to.
        required: true
    artifact_type:
        description: Specifies the app's file type. Can be set to "AAB" or "APK" (default).
        required: false
        default: APK
    build_type:
        description: Build types, can be project-specific, especially with product flavors [release (default), debug]
        required: false
        default: release

runs:
    using: "composite"
    steps:
        -   uses: actions/checkout@v4

        -   name: Prepare Firebase App Distribution configuration
            shell: bash
            run: |
                echo '${{ inputs.credentials_file }}' > photopixels-firebase-appdistribution-private-key.json
                echo 'PHOTOPIXELS_FIREBASE_APPDISTRIBUTION_CREDENTIALS_FILE=photopixels-firebase-appdistribution-private-key.json' > local.properties
                echo 'PHOTOPIXELS_FIREBASE_APPDISTRIBUTION_GROUPS=${{ inputs.groups }}' >> local.properties
                echo 'PHOTOPIXELS_FIREBASE_APPDISTRIBUTION_ARTIFACT_TYPE=${{ inputs.artifact_type }}' >> local.properties
                echo 'PHOTOPIXELS_FIREBASE_APPDISTRIBUTION_BUILD_TYPES=${{ inputs.build_type }}' >> local.properties
                
                pwd
                ls -la
                cat local.properties
