# --------------------------------------------------------------------------------------------------
# This GitHub Actions workflow file defines a reusable workflow that can be shared across jobs.
# It prepares an environment specific version of "google-services.json" and places into the proper
# location on the file system.
# --------------------------------------------------------------------------------------------------

name: Firebase Configuration
description: Prepares Firebase services configuration

inputs:
    google_services_json:
        description: The Firebase Google Services JSON content
        required: true

runs:
    using: "composite"
    steps:
        -   uses: actions/checkout@v4

        -   name: Prepare Firebase services configuration
            shell: bash
            run: |
                echo '${{ inputs.google_services_json }}' > app/google-services.json
