# --------------------------------------------------------------------------------------------------
# This GitHub Actions workflow file defines a reusable workflow that can be shared across jobs.
# It prepares an environment specific version of "google-services.json" and places into the proper
# location on the file system.
# --------------------------------------------------------------------------------------------------

name: Firebase Configuration
description: Prepares Firebase services configuration

inputs:
    google_services_json:
        description: The Firebase Google Services JSON content
        required: true

outputs:
    file_path:
        description: Path to the created file
        value: ${{ steps.create-file.outputs.file_path }}

runs:
    using: "composite"
    steps:
        -   uses: actions/checkout@v4

        -   name: Prepare Firebase services configuration
            id: create-file
            shell: bash
            run: |
                echo '${{ inputs.google_services_json }}' > ${{ github.workspace }}/app/google-services.json
                echo "file_path=$file_path" >> $GITHUB_OUTPUT
