#!/bin/bash

# Get staged files and filter out deleted files and files not ending in ".kt" or ".kts"
STAGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"

if [ -z "$STAGED_FILES" ]; then
    printf "No Kotlin staged files."
    exit 0
fi;

printf "[%s] Running [ktlint] over changed files...\n" "$PWD"
printf "\n%s\n" "$STAGED_FILES"

# Store differences between staged Kotlin files and formatted files in $diff and if any exist,
# apply them recursively on the staged Kotlin files.
diff=.git/unstaged-ktlint-git-hook.diff
git diff --color=never > $diff
if [ -s $diff ]; then
  git apply -R $diff
fi

./gradlew -V ktlintFormat -PinternalKtlintGitFilter="$STAGED_FILES"
gradleCommandExitCode=$?

printf "Completed [ktlint] run."

echo "$STAGED_FILES" | while read -r file; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done

if [ -s $diff ]; then
  git apply --ignore-whitespace $diff
fi
rm $diff
unset diff

printf "Completed [ktlint] checks."
exit $gradleCommandExitCode
