name: Android CI
run-name: ${{ github.actor }} started the Android CI workflow

on:
    push:
        branches:
            - main
            - develop
            - feature/**
            - bugfix/**
            - release/**

    pull_request:
        branches:
            - main
            - develop
            - release/**

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  cache: 'gradle'

            - name: Grant execute permissions for gradlew
              run: chmod +x ./gradlew

            - name: Build with Gradle
              run: ./gradlew build

            - name: Run tests
              run: ./gradlew test

            - name: Create APK release
              run: ./gradlew assembleRelease

            - name: Publish via Firebase AppDistribution
              run: print "TODO"
