# --------------------------------------------------------------------------------------------------
# This GitHub Actions workflow file defines a reusable workflow that can be shared across jobs.
# It prepares an environment specific version of "google-services.json" and places into the proper
# location on the file system.
# --------------------------------------------------------------------------------------------------

name: Firebase Configuration

on:
    workflow_call:
        secrets:
            PHOTOPIXELS_GOOGLE_SERVICES_JSON:
                required: true

jobs:
    firebase-config:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
              
            -   name: Prepare Firebase services configuration
                env:
                    GOOGLE_SERVICES_JSON: ${{ secrets.PHOTOPIXELS_GOOGLE_SERVICES_JSON }}
                run: echo $GOOGLE_SERVICES_JSON > app/google-services.json
